        version: '3.8'

        services:
            casandra:
                image: cassandra:4.0.3
                ports:
                    - "9042:9042"
                environment:
                    - 'CASSANDRA_CLUSTER_NAME=akka-casandra-cluster'